### ISSUE TITLE
Not compatible with other Kotlin lib

### ISSUE THREAD

**Issue by Sikatsu** [TrPlugins/TrMenu#214]
**Describe the bug**
All of a sudden, with no changes on my side, menu's don't work anymore on my lobby server.

Error: https://pastebin.com/niGvwHsR

Command doesn't work, item to trigger the menu works.

**Server Information**
https://hasteb.in/uteqaqah

| TabooLib: 5.4
| TrMenu: 2.06-DEV / Tue Oct 06 04:03:33 CST 2020 (Built by Arasple)

**Comment by Arasple** [comment]
Hello, sorry for the late response.
Please follow the instructions below

1. Stop your server
2. Re-download the [latest artifact](https://github.com/TrMenu/TrMenu/actions/runs/293442363
) of TrMenu and replace it

3. Delete `libs/TabooLib.jar` and `plugins/TabooLib` folder
4. Start your server

**Comment by Sikatsu** [comment]
I have taken the exact steps you mentioned, but my menus still don't work by command..

https://pastebin.com/f0Z5hqmi

**Comment by Sikatsu** [comment]
@Arasple ?

**Comment by plebexer** [comment]
this was also happening to me, i did what you said there and now its woeking

**Comment by plebexer** [comment]
update: it was also happening in another server i tried the same and in that one it did not work
