### ISSUE TITLE
Suggestion: Drag and Drop Event !!!

### ISSUE THREAD

**Issue by golfmaichai1** [TrPlugins/TrMenu#217]
**Type**
Drag and drop event

**Description**
This event will be able player to use custom Reforge item in custom menu witch any condition 

**Usage**
1. open the TrMenu That Have Empty Slot for Dropitem (Custom)
2. Drag the item while open the menu and drop to empty slot
3. the empty slot will check for condition and check for item and return new menu or command or anything

**Example**
<img width="1440" alt="Screen Shot 2019-06-15 at 12 57 23 PM" src="https://user-images.githubusercontent.com/45531631/96332296-46d92080-108d-11eb-8556-28685b0fe081.png">

**Additional context**

**Comment by Rubenicos** [comment]
Use **player.getItemOnCursor()** on action conditions

**Comment by golfmaichai1** [comment]
Can you give e some Example
Im trying but it sho like this


![Uploading ภาพหน้าจอ 2563-10-25 เวลา 01.55.18.png…]()

**Comment by Tanguygab** [comment]
don't try, it's not possible as you can't move items when you have a menu opened. I tried earlier with no success
