### ISSUE TITLE
CustomExpressions

### ISSUE THREAD

**Issue by Enyzat** [TrPlugins/TrMenu#264]
**Describe the bug**
I wanna use a condition like if.%myplaceholder%>{argumentbytrmenu} or with any other placeholders or numbers.
Example:  `- condition: '%mycommand_playerdata_Euro%>{0}'` it doesn't seem to be working:
Sometimes 98 is bigger than 100 and stuff like this happens all t he time

**To Reproduce**
Just use this condition with custom placeholders

**Expected behavior**
Make this function work. Honestly idk if it is implemented right know so I chose bug report, not feature request, because that's an important feature and I believe it should work

**Screenshots**
-

**Additional context**
-

**Server Information**
> Use command `/trmenu dump` to get the information
> Copy the information to below
**it says posted info at "null" so I will write down what I know**
```
TrMenu Dump Information (2020-12-20)

| Server OS: something Linux (I run it at server hosting) idk the name of the distro
| Server software: paper332 1.16.4 R0.1-snapshot 

| TabooLib: 5.45
| TrMenu: 2.08

Installed Plugins: 
A lot (87)
```

**Comment by Tanguygab** [comment]
that's weird, it should work normally,  can you try to send a message to the player with the {0} argument and the other placeholder at the same time that you check the condition?
