### ISSUE TITLE
Kotlin Library incompatibility taboolib #2

### ISSUE THREAD

**Issue by MinecraftAdmin** [TrPlugins/TrMenu#269]
**Describe the bug**
I installed TrMenu and TabooLib fresh on new server. It loads fine, (in the logs) but the /trmenu command does not work and there is error spam in the console.

**Server Information**
I cannot use **/trmenu dump** because _/trmenu command does not work_
But I am running Tuinity 1.16.4 (PaperMC fork)

**Error log:**
https://pastebin.com/raw/8fjrissp

```
TrMenu Dump Information (2020-10-05 20:05:29)

| Server OS: Ubuntu 18.04
| Server software: git-Tuinity-"f06591a" (MC: 1.16.4) (1.16.4-R0.1-SNAPSHOT)
| Java version: 11

| TabooLib: 5.54
| TrMenu: 2.08

Installed Plugins: 
· No other plugins.

**Comment by mrjesen** [comment]
I think,if you donot pay,they will not replay you.
