### ISSUE TITLE
Invalid command execution

### ISSUE THREAD

**Issue by qwe938775** [TrPlugins/TrMenu#283]
actions:
       left:
         - 'command:local

Execute the following command    -'command: local'

Execute the following command    -'console: local'

Execute the following command    -'chat:/local'

Execute the following command    -'op:  local'

https://i.ibb.co/mvychP0/2021-02-06-193102.png

When I want to set a button for multi-chat. I want to set the command button. But there's no way to do it. Players must enter manually in the chat window. /Local will only take effect

Many plug-ins want to make buttons with the same problem

I use this command to test
/trmenu Action ted1212 chat:/local
All invalid

**Comment by Arasple** [comment]
Is `/local` a bungee command?
