### ISSUE TITLE
[问题]: 最新提交无法加载

### ISSUE THREAD

**Issue by xtexChooser** [TrPlugins/TrMenu#379]
- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.
- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.
- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

使用来自GitHub Actions的构建（“Support 1.19 (Preliminarily and untested)”，CI #72，run 2509371402），

配置文件自动生成，未修改任何文件，服务器为Paper 1.12.2-b1551

启动后在加载mongodb依赖时taboolib的`PluginKt#getInstance`中调用`j.l.Class#getSimpleName`时抛出`j.l.InternalError: Malformed class name`

**Comment by xtexChooser** [comment]
cc @Arasple

**Comment by Score2** [comment]
java版本请提供

**Comment by xtexChooser** [comment]
> java版本请提供

AdoptOpenJDK 8u232

**Comment by xtexChooser** [comment]
经测试“Fixed placeholder js bugs.” CI #69可以使用

**Comment by Score2** [comment]
如果可能，请暂时用java11，后续将会重新支持java8
