### ISSUE TITLE
[功能]: 1.19.3适配

### ISSUE THREAD

**Issue by ObcbO** [TrPlugins/TrMenu#393]
### 📚 是否已查阅 Wiki

- [x] 我已查阅 Wiki 并确定没有存在该功能.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 🔍 详细的描述

**适配1.19.3版本**

### ⚙ 配置文件

```

```

**Comment by XiaoJie-150** [comment]
没必要发这个东西,1.19.3都没稳定

**Comment by ObcbO** [comment]
> 没必要发这个东西,1.19.3都没稳定

这不是不支持1.19.3这个正式版的理由啊，我只是提醒下该更新1.19.3了

**Comment by XiaoJie-150** [comment]
等吧,3就更更兼容罢了,不修了,4不知道什么时候出来了

**Comment by Score2** [comment]
兼容1.19.3已经有一段时间了，由于没有更多精力放在v3上，因此未经测试。请更新最新版，如果错误请提供报告。
